<?php
$data=array();
$arr=array ('veh_extfeature' => 'sss',
'id' => '24480' ,
'veh_reg'=> 'HR38LD7437' ,
'veh_status' =>"" ,
'veh_endloc' =>"" ,
'veh_startloc' =>"" , 
'card_number' =>"" ,
'veh_arrivaldate' =>"", 
'veh_departuredate' =>"", 
'veh_destination' =>"", 
'veh_chasis' => "",
'veh_phone_number' =>"", 
'veh_driver_name' => "Spare", 
'speed' => 0, 
'bearing' => 282.0, 
'lastcontact' => '2013-02-25 07:38:23' ,
'aconoff' => 0 ,
'street' => "",
'town' => "",
'country' => "",
'reg' => "HR38LD7437 ",
'disel_datetime' =>"", 
'riwari_in_datetime' =>"", 
'riwari_out_datetime' => "",
'lat' => '28.695808411', 
'lng' => '77.139785767', 
'driver' => "Spare", 
'phone' => "",
'destination' =>"", 
'proximity' => "",
'temperature' => "0.000000000 ",
'poweroff' => 0 ) ;
array_push($data,$arr);

$arr=array ('veh_extfeature' => 'sss',
'id' => '24480' ,
'veh_reg'=> 'HR38LD7432' ,
'veh_status' =>"" ,
'veh_endloc' =>"" ,
'veh_startloc' =>"" , 
'card_number' =>"" ,
'veh_arrivaldate' =>"", 
'veh_departuredate' =>"", 
'veh_destination' =>"", 
'veh_chasis' => "",
'veh_phone_number' =>"", 
'veh_driver_name' => "Spare1", 
'speed' => 23, 
'bearing' => 283.0, 
'lastcontact' => '2013-02-25 07:38:23' ,
'aconoff' => 0 ,
'street' => "",
'town' => "",
'country' => "",
'reg' => "HR38LD7432 ",
'disel_datetime' =>"", 
'riwari_in_datetime' =>"", 
'riwari_out_datetime' => "",
'lat' => '28.695808411', 
'lng' => '77.139785767', 
'driver' => "Spare1", 
'phone' => "",
'destination' =>"", 
'proximity' => "",
'temperature' => "0.000000000 ",
'poweroff' => 0 ) ;
array_push($data,$arr);
print_r($data);


 ?>